live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
blur = true

[window.padding]
x = 15 
y = 15

[scrolling]
history = 100000

[cursor.style]
shape = "block"

[keyboard]
bindings = [
  { key = "Left", mods = "Option", chars = "\u001BB" },
  { key = "Right", mods = "Option", chars = "\u001BF" },
  { key = "Back", mods = "Option", chars = "\u001b\u007f" },
  { key = "Delete", mods = "Option", chars = "\u001bd" },

  { key = "A", mods = "Command", chars = "\u00a4[1;1A" },
  { key = "B", mods = "Command", chars = "\u00a4[1;2B" },
  { key = "C", mods = "Command", chars = "\u00a4[1;3C" },
  { key = "D", mods = "Command", chars = "\u00a4[1;4D" },
  { key = "E", mods = "Command", chars = "\u00a4[1;5E" },
  { key = "F", mods = "Command", chars = "\u00a4[1;6F" },
  { key = "G", mods = "Command", chars = "\u00a4[1;7G" },
  { key = "H", mods = "Command", chars = "\u00a4[1;8H" },
  { key = "I", mods = "Command", chars = "\u00a4[1;9I" },
  { key = "J", mods = "Command", chars = "\u00a4[1;10J" },
  { key = "K", mods = "Command", chars = "\u00a4[1;11K" },
  { key = "L", mods = "Command", chars = "\u00a4[1;12L" },
  { key = "M", mods = "Command", chars = "\u00a4[1;13M" },
  { key = "N", mods = "Command", chars = "\u00a4[1;14N" },
  { key = "O", mods = "Command", chars = "\u00a4[1;15O" },
  { key = "P", mods = "Command", chars = "\u00a4[1;16P" },
  { key = "Q", mods = "Command", chars = "\u00a4[1;17Q" },
  { key = "R", mods = "Command", chars = "\u00a4[1;18R" },
  { key = "S", mods = "Command", chars = "\u00a4[1;19S" },
  { key = "T", mods = "Command", chars = "\u00a4[1;20T" },
  { key = "U", mods = "Command", chars = "\u00a4[1;21U" },
  # { key = "V", mods = "Command", chars = "\u00a4[1;22V" },
  { key = "W", mods = "Command", chars = "\u00a4[1;23W" },
  { key = "X", mods = "Command", chars = "\u00a4[1;24X" },
  { key = "Y", mods = "Command", chars = "\u00a4[1;25Y" },
  { key = "Z", mods = "Command", chars = "\u00a4[1;26Z" },

  { key = "A", mods = "Command|Shift", chars = "\u00a4[1;27A" },
  { key = "B", mods = "Command|Shift", chars = "\u00a4[1;28B" },
  { key = "C", mods = "Command|Shift", chars = "\u00a4[1;29C" },
  { key = "D", mods = "Command|Shift", chars = "\u00a4[1;30D" },
  { key = "E", mods = "Command|Shift", chars = "\u00a4[1;31E" },
  { key = "F", mods = "Command|Shift", chars = "\u00a4[1;32F" },
  { key = "G", mods = "Command|Shift", chars = "\u00a4[1;33G" },
  { key = "H", mods = "Command|Shift", chars = "\u00a4[1;34H" },
  { key = "I", mods = "Command|Shift", chars = "\u00a4[1;35I" },
  { key = "J", mods = "Command|Shift", chars = "\u00a4[1;36J" },
  { key = "K", mods = "Command|Shift", chars = "\u00a4[1;37K" },
  { key = "L", mods = "Command|Shift", chars = "\u00a4[1;38L" },
  { key = "M", mods = "Command|Shift", chars = "\u00a4[1;39M" },
  { key = "N", mods = "Command|Shift", chars = "\u00a4[1;40N" },
  { key = "O", mods = "Command|Shift", chars = "\u00a4[1;41O" },
  { key = "P", mods = "Command|Shift", chars = "\u00a4[1;42P" },
  { key = "Q", mods = "Command|Shift", chars = "\u00a4[1;43Q" },
  { key = "R", mods = "Command|Shift", chars = "\u00a4[1;44R" },
  { key = "S", mods = "Command|Shift", chars = "\u00a4[1;45S" },
  { key = "T", mods = "Command|Shift", chars = "\u00a4[1;46T" },
  { key = "U", mods = "Command|Shift", chars = "\u00a4[1;47U" },
  { key = "V", mods = "Command|Shift", chars = "\u00a4[1;48V" },
  { key = "W", mods = "Command|Shift", chars = "\u00a4[1;49W" },
  { key = "X", mods = "Command|Shift", chars = "\u00a4[1;50X" },
  { key = "Y", mods = "Command|Shift", chars = "\u00a4[1;51Y" },
  { key = "Z", mods = "Command|Shift", chars = "\u00a4[1;52Z" },

  { key = "/", mods = "Command", chars = "\u00a4[1;53/" },

  # { key = "[", mods = "Command", chars = "\u00a4[1;100[" },
  # { key = "]", mods = "Command", chars = "\u00a4[1;101]" },
  { key = "{", mods = "Command|Shift", chars = "\u00a4[1;102{" },
  { key = "}", mods = "Command|Shift", chars = "\u00a4[1;103}" },
  { key = "<", mods = "Command|Shift", chars = "\u00a4[1;104<" },
  { key = ">", mods = "Command|Shift", chars = "\u00a4[1;105>" },
  { key = 'Down', mods = "Command|Option", chars = "\u00a4[1;106D" },
  { key = 'Down', mods = "Command", chars = "\u00a4[1;107D" },
  { key = 'Up', mods = "Command|Option", chars = "\u00a4[1;108U" },
  { key = 'Up', mods = "Command", chars = "\u00a4[1;109U" },
  { key = 'Enter', mods = "Command", chars = "\u00a4[1;110E" },
  { key = 'Enter', mods = "Command|Shift", chars = "\u00a4[1;111E" }, 
  { key = 'Backspace', mods = "Command", chars = "\u00a4[1;112B" }, 
  { key = 'Backspace', mods = "Command|Shift", chars = "\u00a4[1;113B" }, 
  { key = 'Delete', mods = "Command", chars = "\u00a4[1;114D" }, 
  { key = 'Delete', mods = "Command|Shift", chars = "\u00a4[1;115D" }, 

  { key = "Left", mods = "Command|Shift", chars = "\u00a4[1;116L" },

]

