live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
blur = true

[window.padding]
x = 15 
y = 15

[scrolling]
history = 100000

[cursor.style]
shape = "block"

[keyboard]
bindings = [
  { key = "Left", mods = "Option", chars = "\u001BB" },
  { key = "Right", mods = "Option", chars = "\u001BF" },
  { key = "Back", mods = "Option", chars = "\u001b\u007f" },
  { key = "Delete", mods = "Option", chars = "\u001bd" },

  { key = "A", mods = "Command", chars = "\u002b[1;1A" },
  { key = "B", mods = "Command", chars = "\u002b[1;2B" },
  { key = "C", mods = "Command", chars = "\u002b[1;3C" },
  { key = "D", mods = "Command", chars = "\u002b[1;4D" },
  { key = "E", mods = "Command", chars = "\u002b[1;5E" },
  { key = "F", mods = "Command", chars = "\u002b[1;6F" },
  { key = "G", mods = "Command", chars = "\u002b[1;7G" },
  { key = "H", mods = "Command", chars = "\u002b[1;8H" },
  { key = "I", mods = "Command", chars = "\u002b[1;9I" },
  { key = "J", mods = "Command", chars = "\u002b[1;10J" },
  { key = "K", mods = "Command", chars = "\u002b[1;11K" },
  { key = "L", mods = "Command", chars = "\u002b[1;12L" },
  { key = "M", mods = "Command", chars = "\u002b[1;13M" },
  { key = "N", mods = "Command", chars = "\u002b[1;14N" },
  { key = "O", mods = "Command", chars = "\u002b[1;15O" },
  { key = "P", mods = "Command", chars = "\u002b[1;16P" },
  { key = "Q", mods = "Command", chars = "\u002b[1;17Q" },
  { key = "R", mods = "Command", chars = "\u002b[1;18R" },
  { key = "S", mods = "Command", chars = "\u002b[1;19S" },
  { key = "T", mods = "Command", chars = "\u002b[1;20T" },
  { key = "U", mods = "Command", chars = "\u002b[1;21U" },
  # { key = "V", mods = "Command", chars = "\u002b[1;22V" },
  { key = "W", mods = "Command", chars = "\u002b[1;23W" },
  { key = "X", mods = "Command", chars = "\u002b[1;24X" },
  { key = "Y", mods = "Command", chars = "\u002b[1;25Y" },
  { key = "Z", mods = "Command", chars = "\u002b[1;26Z" },

  { key = "A", mods = "Command|Shift", chars = "\u002b[1;27A" },
  { key = "B", mods = "Command|Shift", chars = "\u002b[1;28B" },
  { key = "C", mods = "Command|Shift", chars = "\u002b[1;29C" },
  { key = "D", mods = "Command|Shift", chars = "\u002b[1;30D" },
  { key = "E", mods = "Command|Shift", chars = "\u002b[1;31E" },
  { key = "F", mods = "Command|Shift", chars = "\u002b[1;32F" },
  { key = "G", mods = "Command|Shift", chars = "\u002b[1;33G" },
  { key = "H", mods = "Command|Shift", chars = "\u002b[1;34H" },
  { key = "I", mods = "Command|Shift", chars = "\u002b[1;35I" },
  { key = "J", mods = "Command|Shift", chars = "\u002b[1;36J" },
  { key = "K", mods = "Command|Shift", chars = "\u002b[1;37K" },
  { key = "L", mods = "Command|Shift", chars = "\u002b[1;38L" },
  { key = "M", mods = "Command|Shift", chars = "\u002b[1;39M" },
  { key = "N", mods = "Command|Shift", chars = "\u002b[1;40N" },
  { key = "O", mods = "Command|Shift", chars = "\u002b[1;41O" },
  { key = "P", mods = "Command|Shift", chars = "\u002b[1;42P" },
  { key = "Q", mods = "Command|Shift", chars = "\u002b[1;43Q" },
  { key = "R", mods = "Command|Shift", chars = "\u002b[1;44R" },
  { key = "S", mods = "Command|Shift", chars = "\u002b[1;45S" },
  { key = "T", mods = "Command|Shift", chars = "\u002b[1;46T" },
  { key = "U", mods = "Command|Shift", chars = "\u002b[1;47U" },
  { key = "V", mods = "Command|Shift", chars = "\u002b[1;48V" },
  { key = "W", mods = "Command|Shift", chars = "\u002b[1;49W" },
  { key = "X", mods = "Command|Shift", chars = "\u002b[1;50X" },
  { key = "Y", mods = "Command|Shift", chars = "\u002b[1;51Y" },
  { key = "Z", mods = "Command|Shift", chars = "\u002b[1;52Z" },

  { key = "/", mods = "Command", chars = "\u002b[1;53/" },
  { key = "[", mods = "Command", chars = "\u002b[1;100[" },
  { key = "]", mods = "Command", chars = "\u002b[1;101]" },
  { key = "{", mods = "Command|Shift", chars = "\u002b[1;102{" },
  { key = "}", mods = "Command|Shift", chars = "\u002b[1;103}" },

]

